### ISSUE TITLE
Thumbnails of deleted images remain in the upload gallery

### ISSUE THREAD

**Issue by metatraveller** [mapillary/mapillary_windows_phone#1]
The thumbnails of deleted images remain in the upload gallery. If the thumbnail of the deleted image is pressed one gets an error message which states  that the image doesn't exist.

Could it be possible to refresh the gallery after one returns to the upload gallery from the deleting sequence of a picture? Then the thumbnails of deleted pictures would also be deleted.

**Comment by ovesennet** [comment]
Unable to reproduce. Can you explain exactly what you do ?
Have you enabled the setting "Store photos in camera roll instead of internal app storage."
Can reinstall the app ? Does this still happen?

**Comment by metatraveller** [comment]
I made a short session and started to delete photos and now it works without the error messages. I didn't reinstall the app.

The photos were stored in internal app storage.

If the error messages show up again, I'll take a screen shot.

**Comment by bdhurkett** [comment]
I occasionally run into this - it seems to happen when I look through several photos (i.e. tapping 'Next >>') and then delete one; the full-size photo can't be displayed (it shows "Error loading photo:" and then the previous image with the deleted photo's number) but the thumbnail remains until I back out of the screen/app.

When this happens, the error comes up whether I tap on the thumbnail directly, or click 'Next >>' from the previous photo.

**Comment by ovesennet** [comment]
I'll look into it.

**Comment by ovesennet** [comment]
Fixed the issue. Look for update 1.1.0.3
