### ISSUE TITLE
Captures are oriented upside down

### ISSUE THREAD

**Issue by bdhurkett** [mapillary/mapillary_windows_phone#2]
My phone was rotated 90 degrees clockwise for the best view in the holder when driving. Mapillary recognised the phone was in landscape, and the viewfinder display and UI were correctly oriented, and the capture process seemed fine, but all the photos in the upload window are upside down.

The results of some quick experimenting:
* If I rotate the phone to the left (counterclockwise) upon entering the capture mode, photos are oriented correctly
* If I rotate the phone to the right upon entering the capture mode, photos are oriented **incorrectly**
* If I rotate the phone to the left, and *then* to the right, photos are oriented correctly. 

![wp_ss_20150605_0001](https://cloud.githubusercontent.com/assets/8445671/7999427/1b3fe026-0b8e-11e5-8dd9-d8b1702f9643.png)

**Comment by ovesennet** [comment]
Thanks for reporting. I can confirm that this is a bug and I'm looking into it ASAP

**Comment by ovesennet** [comment]
Update 1.1.0.1 has been submitted
