### ISSUE TITLE
Pausing in riding mode when stationary - supported?

### ISSUE THREAD

**Issue by bdhurkett** [mapillary/mapillary_windows_phone#4]
http://www.mapillary.com/using.html includes a mention of this feature:
>In riding mode the app also pauses when you stand still. For example at a stop light. Capture will resume once you start moving again.

Is this currently supported in the Windows Phone app? It doesn't seem to happen in my captures, but I don't know if it should be.

**Comment by ovesennet** [comment]
Hi, unfortunately it's not supported in the WP app. I will look into it.

**Comment by ovesennet** [comment]
Fixed in update 1.1.1.0

**Comment by bdhurkett** [comment]
You're amazing.
