### ISSUE TITLE
Indicator on login screen

### ISSUE THREAD

**Issue by bdhurkett** [mapillary/mapillary_windows_phone#5]
A minor request/suggestion - display some kind of progress/status indicator on the login screen, while actually logging in. Like those dots going across the top when the recent events list is loading, just to show it's doing something.

Nothing is broken with actually getting logged in, but on the rare occasion I have to do it, it takes a few seconds, and I'm never quite sure if anything is happening or whether it even registered my pressing the submit button. Even when I get it right first go it's a little disconcerting.

**Comment by ovesennet** [comment]
Thanks, I'll fix that for the next release :-)
